"""The markdown `python -m bench` writes, and the order it insists on.

The caveats come before the first number, because a table read without them is a
table read wrongly. Then the machine, then the method, then the results, then how
far the repeats were apart -- so that a reader reaches the findings already
knowing the noise floor and can refuse to believe a difference smaller than it.

Everything this module writes is derived from the run. The reading of the
results -- what was confirmed, what changed, what an operator should do -- is
written by hand under the `READING` heading, and `bench.__main__` refuses to
overwrite a report that has one unless it is told to.
"""

import textwrap
from collections.abc import Sequence
from dataclasses import dataclass

from bench.baseline import BaselinePoint, Share
from bench.environment import Environment
from bench.harness import Summary, significant
from bench.recording import Recording
from bench.runner import Cache
from bench.sweep import Cell, Isolation, Point, Sweep
from bench.workloads import WORKLOADS

__all__ = ["READING", "Results", "render"]

# Where the generated document stops and the hand-written reading of it starts.
READING = "## Reading"


@dataclass(frozen=True)
class Results:
    """One run of the benchmark: what was measured, and what it was measured on."""

    environment: Environment
    command: str
    seconds: float
    # Why there are no cold-cache runs, or `None` when there are some. Carried
    # rather than derived: `--warm-only` on a machine that *can* drop its page
    # cache is a different sentence from a machine that cannot, and the
    # environment table three sections below says which machine this is.
    cold_skipped: str | None
    baseline: tuple[BaselinePoint, ...] = ()
    share: Share | None = None
    recording: tuple[Recording, ...] = ()
    sweep: Sweep | None = None
    isolation: Isolation | None = None


def _wrapped(text: str) -> str:
    """One paragraph, re-wrapped. For prose with numbers interpolated into it.

    A template that interpolates a two-character number into a fixed layout wraps
    wherever the template happened to break, which in a diff of two runs looks
    like the prose changed. Collapsing and re-wrapping keeps the source readable
    and makes one run's report diff against another's in the numbers alone.
    """
    return textwrap.fill(" ".join(text.split()), width=96)


def render(results: Results) -> str:
    """The whole document, in the order it has to be read in."""
    sections = [
        _caveats(results),
        _environment(results.environment),
        _method(results),
        *_baseline(results),
        *_share(results),
        *_recording(results),
        *_sweep(results),
        *_isolation(results),
        *_repeatability(results),
        _derived(results),
    ]
    return "\n\n".join(section.strip() for section in sections if section.strip()) + "\n"


def _caveats(results: Results) -> str:
    cold = (
        """**What "cold" can mean here.** A cold run drops each instance's pages from this guest's
page cache with `posix_fadvise(DONTNEED)`. The host's cache and the hypervisor's are not ours to
drop, so a cold read here is a read that missed *this* machine's cache and may well have been
served by one below it. Treat the cold figures as a floor on how fast cold can be, not as a
measurement of a cold disk."""
        if results.cold_skipped is None
        else _wrapped(f"""**Cold-cache runs were skipped: {results.cold_skipped}.** A warm number
printed under a cold heading would be worse than no number at all.""")
    )
    return f"""# Seahaven benchmark: latest results

Generated by `{results.command}` in {significant(results.seconds)} s. Everything above the
`{READING}` heading is generated; the reading below it was written by hand from these tables.

## What these numbers are, and what they are not

**They are one machine, one afternoon.** The run below happened inside a shared, virtualised
sandbox: a few vCPUs of a host we do not own, no CPU pinning, no control over what else was
running, and a filesystem nobody would deploy on. Every figure carries the spread of its own
repeats; differences smaller than that spread are noise, and this document rounds everything to
two significant figures because a third would be a fiction.

**Use them for:** the order of magnitude of a call; the *shape* of a curve (what happens to
throughput and to waiting as the concurrency gate changes); and comparison against another run of
this same harness on this same machine -- which is how a regression is found.

**Do not use them for:** capacity planning, hardware comparison, a service-level objective, a
claim in a README, or a comparison with any other framework's benchmark. The latency columns come
from a closed loop with no think time: every session issues its next call the instant the last
returns, so the process is saturated throughout and the percentiles are the queueing of that
offered load. They are not what a session would see on a server that is not saturated.

**This is never a gate.** The benchmark is not in CI, nothing fails on a number, and no threshold
is asserted anywhere. `tests/test_bench.py` proves the harness still runs; it does not check a
speed.

{cold}"""


def _environment(environment: Environment) -> str:
    rows = "\n".join(f"| {label} | {value} |" for label, value in environment.rows())
    return f"## Environment\n\n| | |\n|---|---|\n{rows}"


def _method(results: Results) -> str:
    sweep = results.sweep
    workloads = (
        "\n".join(
            f"- **`{name}`**: {_workload_description(name)}" for name in _workloads_run(results)
        )
        or "- (no workload was run)"
    )
    sweep_lines = (
        "\n"
        + _wrapped(
            f"**The gate sweep.** Gate sizes {_numbers(sweep.gates)} (`0` is no gate, the "
            f"control) x offered load {_numbers(sweep.workers)} sessions x cache "
            f"{', '.join(sweep.caches)} x workload "
            f"{', '.join(f'`{name}`' for name in sweep.workloads)}, {sweep.repeats} repeats, "
            f"{sweep.calls} calls per session per pass, seed {sweep.seed}. The gate is set "
            "through `seahaven.instances.set_concurrency`, which is what `seahaven serve "
            "--concurrency` calls. Each repeat is a whole pass over every point in a seeded "
            f"shuffle, so drift over the {significant(sweep.seconds)} s the sweep took is spread "
            "across the configurations rather than handed to whichever ran last."
        )
        if sweep is not None
        else ""
    )
    return f"""## Method

**The world.** ProjectTracker `agency`, the framework's largest fixture: twelve people, nine
projects, six hundred issues with six months of history. Every call goes through
`Instance.call`, which is the path an eval takes -- argument validation, the middleware chain,
the per-call transaction, the tool, the change log's session, the serialiser.

**The workloads.**

{workloads}

**One instance per session.** An instance serialises its own calls under its lock, so every
worker thread gets its own instance -- a private copy of the fixture, which is how OpenEnv
serves sessions.

**Warm and cold.** *Warm* means the session has already served one full pass of its workload,
so its connection's page cache holds what the pass touches. *Cold* means the instance has served
nothing and its files have been evicted from this guest's page cache. Both are measured with a
fixed number of calls per session, so two passes of one configuration do identical work.

**The write mix's warm and cold columns differ by more than a cache.** Its warm-up writes as many
rows as the measured pass will, so a warm write pass runs on an instance carrying a pass worth of
extra rows and log records while a cold one runs on a virgin instance. An instance's write
cost climbs with those rows by roughly the size of the gap between the two columns, so the write
mix's cold/warm axis mixes cache state with accumulated state and should not be read as a cache
effect. The read workload has no such confound: it writes nothing.

**Logging.** The `seahaven` logger is pinned to WARNING for the run, so the one INFO line every
call emits costs a level check and nothing else. Under `seahaven serve`, uvicorn configures INFO
handlers and that line is formatted and written; this benchmark does not measure that.
{sweep_lines}

**Reproducing it.** From the repository root, on the commit named above:

```
{results.command}
```"""


def _baseline(results: Results) -> list[str]:
    if not results.baseline:
        return []
    rows = "\n".join(
        f"| `{point.workload}` | {point.cache} | {point.calls_per_pass} | "
        f"{significant(point.summary.rate_median)} | {_range(point.summary)} | "
        f"{_ms(point.summary.p50)} | {_ms(point.summary.p95)} | {_ms(point.summary.worst)} |"
        for point in results.baseline
    )
    return [
        f"""## 1. Baseline: one session, one thread

What a call costs with nothing else running. `functional_spec.md` §23 asks for "about 3,000
one-row reads per second per process"; the `read` rows are that number.

| Workload | Cache | Calls/pass | Calls/s | min-max | p50 | p95 | worst |
|---|---|---:|---:|---|---:|---:|---:|
{rows}

Latencies are per call, in milliseconds, pooled over the repeats."""
    ]


def _share(results: Results) -> list[str]:
    share = results.share
    if share is None:
        return []
    db_percent = round(share.fraction_of_call(share.db_seconds) * 100)
    cursor_percent = round(share.fraction_of_call(share.cursor_seconds) * 100)
    supported = _wrapped(
        f'What this supports is §23\'s "the framework layer, not SQLite, as the per-call cost": '
        f"about {100 - cursor_percent}% of a one-row read is Seahaven, of which roughly "
        f"{db_percent - cursor_percent} points are the data layer and the rest is dispatch. "
        f"From {share.calls} calls down each leg."
    )
    return [
        f"""## 2. Where a one-row read goes

The same `get_issue`, on one instance, driving the same rows in the same order, warm, timed three
ways: through `Instance.call`; as the two statements the tool runs (the issue's row, then its
labels) through `Db.rows`, which is the data layer world code is handed; and as those same two
statements stepped straight on the APSW cursor.

| | Per call | Share of the call |
|---|---:|---:|
| Through `Instance.call` | {_ms(share.call_seconds)} | 100% |
| The two statements through `Db.rows` | {_ms(share.db_seconds)} | ~{db_percent}% |
| The same two statements on the APSW cursor | {_ms(share.cursor_seconds)} | ~{cursor_percent}% |

The middle row is **not** SQLite's share: `Db.rows` is framework code -- an error-translating
context manager, and a dict built per row from the cursor description -- so counting it as SQLite
would book half the data layer to the database. The bottom row is the closest this can get to
SQLite proper, and it is still an upper bound: the statements are stepped on the inspection
connection, whose read-only authorizer runs a Python callback while SQLite prepares them.

{supported}"""
    ]


def _recording(results: Results) -> list[str]:
    if not results.recording:
        return []
    rows = "\n".join(_recording_rows(probe) for probe in results.recording)
    findings = "\n\n".join(_wrapped(_recording_finding(probe)) for probe in results.recording)
    calls = min(probe.calls for probe in results.recording)
    # Only when this run produced one: a standalone `recording` report has no
    # noise floor of its own to point at.
    floor = (
        " Read the totals against section 6's noise floor before calling them a difference, and"
        if results.sweep is not None
        else " Read the totals as approximate, and"
    )
    return [
        f"""## 3. What the change log costs a call

Each workload on one instance, recorded three ways. The first is what Seahaven does: a session
opened and attached per call, its changeset read when the call's transaction is done, and the
records rendered into the log. The second opens and attaches the same session per call and reads
nothing out of it, so the gap to the first is `changeset()` and `render_log`. The third is the
shape before this release, one session for the whole pass and read by nobody, so the gap to the
second is everything a *fresh* session does that a warmed-up one does not: opening it, attaching
its tables, its first sighting of each table it records, and freeing a populated change buffer at
`close()`. Neither of the last two is a configuration Seahaven offers.

| Workload | Leg | Per call | Against one session |
|---|---|---:|---:|
{rows}

{findings}

{
            _wrapped(
                f"From {calls} calls down each leg, alternated pass by pass so that an instance's "
                "write cost climbing with its own rows is not handed to whichever leg ran last."
                f"{floor} read the *split* more loosely still: the fresh-session leg is the "
                "noisiest of the three and has been seen to move by more than its own size "
                "between runs, while the rendering share holds. What that leg is made of differs "
                "by workload, and this probe does not separate the pieces -- read the per-workload "
                "findings above for which of them can be doing the work at all."
            )
        }"""
    ]


def _recording_rows(probe: Recording) -> str:
    """One workload's three legs.

    The stable share is rounded and the noisy one takes the remainder, so the
    middle row and the finding below the table cannot disagree by a point. A
    workload that wrote no rows gets no middle figure at all: there is nothing
    for the leg above it to have rendered, so whatever separates them is noise,
    and printing it as a percentage would invite it to be read.
    """
    total = round(probe.overhead * 100)
    rendering = round(probe.rendering * 100)
    middle = f"{total - rendering:+d}%" if probe.wrote_rows else "noise"
    return "\n".join(
        (
            f"| `{probe.workload}` | a session per call | {_ms(probe.per_call_seconds)} "
            f"| {total:+d}% |",
            f"| `{probe.workload}` | a session per call, never read | {_ms(probe.unread_seconds)} "
            f"| {middle} |",
            f"| `{probe.workload}` | one long-lived session | {_ms(probe.long_lived_seconds)} "
            f"| -- |",
        )
    )


def _recording_finding(probe: Recording) -> str:
    total = round(probe.overhead * 100)
    rendering = round(probe.rendering * 100)
    if not probe.wrote_rows:
        return (
            f"**`{probe.workload}`** costs about {total:+d}% against the framework's previous "
            "shape. No call of the pass gave its session a row, so there was nothing to render "
            "and nothing to free: what it pays is a session opened and attached per call, and an "
            "empty `changeset()` read back. Its two comparison legs therefore differ by that "
            "empty read alone, so whatever separates them here is not a measurement of anything "
            "and the split is left unreported."
        )
    return (
        f"**`{probe.workload}`** costs about {total:+d}% against the framework's previous shape, "
        f"of which roughly {rendering:+d} points are reading the changeset and rendering the "
        f"records and the remaining {total - rendering:+d} are what a fresh session per call costs "
        "over a warmed-up one. The first of those is work that used to happen once an episode, "
        "when an eval asked for the changeset; it happens per call now, because a per-call record "
        "is what the change log is."
    )


def _sweep(results: Results) -> list[str]:
    sweep = results.sweep
    if sweep is None:
        return []
    sections = [
        """## 4. The gate sweep

One table per workload and cache state. **Calls/s** is the whole process: every session's calls
over the pass's wall time. **spread** is (max - min) / median over the repeats -- this cell's own
noise. **worst** is the longest any single call waited.

Two things these tables cannot show. **Fairness**, except through `worst`: every session is given
the same number of calls, so a pass does not end until the worst-served one has had all of them,
and a count per session would read the same at every gate size. Section 5, which is bounded by
time rather than by calls, is where unfairness is visible. And **`Calls/s` and `worst` are not
independent**: a pass ends when its slowest session finishes, so a configuration that leaves one
session waiting also spends the tail of its pass below full load, which lowers the rate of exactly
the configurations that score badly on waiting."""
    ]
    for workload in sweep.workloads:
        for cache in sweep.caches:
            rows = [
                cell
                for cell in sweep.cells
                if cell.point.workload == workload and cell.point.cache == cache
            ]
            if rows:
                sections.append(_sweep_table(workload, cache, rows))
    return sections


def _sweep_table(workload: str, cache: Cache, cells: Sequence[Cell]) -> str:
    ordered = sorted(cells, key=lambda cell: (cell.point.workers, _gate_order(cell.point.gate)))
    rows = "\n".join(
        f"| {cell.point.workers} | {_gate(cell.point.gate)} | "
        f"{significant(cell.summary.rate_median)} | {round(cell.summary.spread * 100)}% | "
        f"{_ms(cell.summary.p50)} | {_ms(cell.summary.p95)} | {_ms(cell.summary.worst)} |"
        for cell in ordered
    )
    return f"""### `{workload}`, {cache} cache

| Sessions | Gate | Calls/s | spread | p50 | p95 | worst |
|---:|---:|---:|---:|---:|---:|---:|
{rows}"""


def _isolation(results: Results) -> list[str]:
    probe = results.isolation
    if probe is None or not probe.cells:
        return []
    rows = "\n".join(
        f"| {_gate(cell.gate)} | {significant(cell.readers.rate_median)} | "
        f"{_ms(cell.readers.p50)} | {_ms(cell.readers.p95)} | {_ms(cell.readers.worst)} | "
        f"{min(cell.worst_window)}-{max(cell.worst_window)} | "
        f"{significant(cell.slow.rate_median)} | {_ms(cell.slow.p50)} |"
        for cell in probe.cells
    )
    intro = _wrapped(
        f"{probe.readers} sessions reading one row at a time, beside one session looping a slow "
        f"`run_sql` self-join, for {significant(probe.seconds)} s at each gate size, "
        f"{_times(probe.repeats)} over. The question a sweep of short calls cannot ask: what a "
        f"gate size does to everybody else when one call is slow."
    )
    return [
        f"""## 5. One slow call, {probe.readers} ordinary sessions

{intro}

| Gate | Reader calls/s | p50 | p95 | worst | calls per reader | Slow calls/s | Slow p50 |
|---:|---:|---:|---:|---:|---|---:|---:|
{rows}

"calls per reader" is the worst-served and best-served reader **within one window** -- the window
in which the worst-served reader did least, out of the repeats -- so the two counts are two
sessions that really were running side by side. It is what this section exists for: the rate and
the quantiles average over readers that were served and readers that were not.

Both rate columns are divided by a window that includes the drain after it closes -- a caller
blocked on the gate when the window ends still has to take a slot and run before it can stop --
which understates them by a few percent, most at the gate sizes that make callers wait. The counts
per reader are unaffected."""
    ]


def _repeatability(results: Results) -> list[str]:
    sweep = results.sweep
    if sweep is None or not sweep.cells:
        return []
    spreads = sorted(cell.summary.spread for cell in sweep.cells)
    worst = max(sweep.cells, key=lambda cell: cell.summary.spread)
    control = _control(sweep)
    passes = " → ".join(
        f"{significant(rate)} at {offset:.0f} s"
        for rate, offset in zip(control.rates, control.offsets, strict=True)
    )
    median_spread = spreads[len(spreads) // 2]
    return [
        f"""## 6. Repeatability, and the noise floor

Each cell was measured {_times(sweep.repeats)}, in a different order each pass.

| | |
|---|---|
| Median spread across cells | {round(median_spread * 100)}% |
| Worst spread | {round(worst.summary.spread * 100)}% ({_point(worst.point)}) |
| Drift check | `{_point(control.point)}`: {passes} |

The drift check is one configuration's passes in the order they ran, spread through the sweep.
Half the cells moved by more than the median, so the median is a floor on this machine's noise and
not a threshold: a difference between two cells smaller than the median is not a difference this
machine can see at all, and one smaller than the worst spread above deserves no weight without
more repeats than this run had."""
    ]


def _control(sweep: Sweep) -> Cell:
    """The cell whose repeats are shown as the drift check.

    A fixed choice rather than an interesting one: the first workload, the first
    cache state, the smallest offered load and the ungated process. It is in the
    report to show how much the machine moved during the sweep, so it has to be
    the same configuration from one run to the next.
    """
    wanted = Point(
        workload=sweep.workloads[0],
        cache=sweep.caches[0],
        workers=min(sweep.workers),
        gate=0 if 0 in sweep.gates else sweep.gates[0],
    )
    return sweep.cell(wanted) or sweep.cells[0]


def _derived(results: Results) -> str:
    """The comparisons a reader would otherwise do on the tables by hand.

    Derived, not interpreted: the quickest gate in each row, how the cpu-derived
    default did against it, and how the ungated control did against the default
    on both throughput and waiting. What any of it means is the hand-written
    reading's job -- but leaving the control out of the table would leave the one
    comparison the sweep exists to make to prose alone.
    """
    sweep = results.sweep
    if sweep is None:
        return ""
    default = results.environment.default_gate
    lines = []
    for workload in sweep.workloads:
        for cache in sweep.caches:
            for workers in sweep.workers:
                cells = [
                    cell
                    for cell in sweep.cells
                    if cell.point.workload == workload
                    and cell.point.cache == cache
                    and cell.point.workers == workers
                ]
                if not cells:
                    continue
                best = max(cells, key=lambda cell: cell.summary.rate_median)
                at_default = _at_gate(cells, default)
                ungated = _at_gate(cells, 0)
                lines.append(
                    f"| `{workload}` | {cache} | {workers} | {_gate(best.point.gate)} | "
                    f"{significant(best.summary.rate_median)} | "
                    f"{_against_default(best, at_default, default)} | "
                    f"{_rate_and_worst(at_default)} | {_rate_and_worst(ungated)} |"
                )
    table = "\n".join(lines)
    intro = _wrapped(
        "Arithmetic on the tables above, not a conclusion about them. The last two columns are "
        f"calls/s and the worst observed wait, for the default this machine computes ({default}) "
        "and for the ungated control."
    )
    return f"""## 7. Derived: the quickest gate, the default, and no gate at all

{intro}

{_derived_header(default)}
{table}"""


def _derived_header(default: int) -> str:
    columns = (
        "Workload",
        "Cache",
        "Sessions",
        "Quickest gate",
        "Its calls/s",
        "Against the default",
        f"Default {default}",
        "No gate",
    )
    return f"| {' | '.join(columns)} |\n|---|---|---:|---:|---:|---|---|---|"


def _against_default(best: Cell, at_default: Cell | None, default: int) -> str:
    """How the cpu-derived default did in this row, against the row's best."""
    if at_default is None:
        return f"the default ({default}) was not measured here"
    if at_default is best:
        return "which is the default"
    percent = round(at_default.summary.rate_median / best.summary.rate_median * 100)
    return f"the default ({default}) is at {percent}% of it"


def _at_gate(cells: Sequence[Cell], gate: int) -> Cell | None:
    return next((cell for cell in cells if cell.point.gate == gate), None)


def _rate_and_worst(cell: Cell | None) -> str:
    if cell is None:
        return "not measured"
    return f"{significant(cell.summary.rate_median)}, worst {_ms(cell.summary.worst)}"


def _workloads_run(results: Results) -> list[str]:
    """Every workload this run drove, in the order it first drove them.

    From all three measurements and not only the baseline: a run of the isolation
    probe alone still drove a workload, and a method section that says none was
    run is a method section describing a different run.
    """
    names = [point.workload for point in results.baseline]
    if results.sweep is not None:
        names += list(results.sweep.workloads)
    if results.isolation is not None and results.isolation.cells:
        names.append(results.isolation.workload)
    return list(dict.fromkeys(names))


def _workload_description(name: str) -> str:
    workload = WORKLOADS.get(name)
    return workload.description if workload is not None else name


def _times(count: int) -> str:
    return "once" if count == 1 else f"{count} times"


def _numbers(values: Sequence[int]) -> str:
    return ", ".join(str(value) for value in values)


def _gate(size: int) -> str:
    return "none" if size == 0 else str(size)


def _gate_order(size: int) -> tuple[int, int]:
    """`0` means no gate, so it sorts last rather than first."""
    return (1, 0) if size == 0 else (0, size)


def _ms(seconds: float) -> str:
    return f"{significant(seconds * 1000)} ms"


def _range(summary: Summary) -> str:
    return f"{significant(summary.rate_min)}-{significant(summary.rate_max)}"


def _point(point: Point) -> str:
    return f"{point.workload}, {point.cache}, {point.workers} sessions, gate {_gate(point.gate)}"
